name: Build, Test, and Deploy Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Krok 1: Pobranie kodu
    - name: Checkout code
      uses: actions/checkout@v2

    # Krok 2: Instalacja Pythona i zależności
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # # Krok 3: Uruchomienie testów
    # - name: Run Tests
    #   run: pytest

    # Krok 4: Konfiguracja Dockera
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Krok 5: Budowanie i wypchnięcie obrazu Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple_web_app:latest
